# 追加补丁路径
FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SRC_URI:append = " file://cst128a-driver-complete.patch "

# 启用 CST128A 驱动（编译进内核，y 表示编译进内核，m 表示模块）
#KERNEL_CONFIG_FRAGMENTS += "${THISDIR}/files/cst128a.cfg"

KERNEL_EXTRA_ARGS += "CONFIG_TOUCHSCREEN_CST128A=y"
KERNEL_EXTRA_ARGS += "CONFIG_INPUT=y"
KERNEL_EXTRA_ARGS += "CONFIG_INPUT_TOUCHSCREEN=y"
KERNEL_EXTRA_ARGS += "CONFIG_INPUT_EVDEV=y"
KERNEL_EXTRA_ARGS += "CONFIG_I2C=y"
KERNEL_EXTRA_ARGS += "CONFIG_I2C_CHARDEV=y"
